name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DB_HOST: mysql
      DB_PORT: 3306
      MYSQL_PORT: 3307
      
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: aitaxcalcpassword
          MYSQL_DATABASE: aitaxcalcdb
          MYSQL_USER: aitaxcalcuser
          MYSQL_PASSWORD: aitaxcalcpassword
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env file for backend
        run: |
          cp .env.example ai-tax-calc-backend/.env

      # Step 3: Install and test the backend
      - name: Install Backend Dependencies
        run: |
          cd ai-tax-calc-backend
          npm install
      - name: Run Backend Tests
        run: |
          cd ai-tax-calc-backend
          npm test

      # Step 4: Install and test the frontend
      - name: Install Frontend Dependencies
        run: |
          cd ai-tax-calc
          npm install
      - name: Run Frontend Tests
        run: |
          cd ai-tax-calc
          npm test

      # Step 5: Build and validate Docker Compose
      - name: Build and Test Docker Compose
        run: |
          docker compose up --build -d
          docker compose ps
